#!/bin/bash

scriptdir=$(dirname "${BASH_SOURCE[0]}")

# install oh-my-zsh if missing
if [[ -d ~/.oh-my-zsh ]]; then
    echo "Info: oh my zsh already installed. Upgrading..."
    zsh -ic upgrade_oh_my_zsh
else
    wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O - | zsh
    chsh -s $(which zsh)
fi

# substitute variables in .zshrc
genrcin=${scriptdir}/genrc.symlink.in
genrcout=${scriptdir}/genrc.symlink
cat << EOF > "${genrcout}"
# WARNING: The contents of this file are autogenerated by the autoconfig
# install script. To edit this file, you must edit the file at
# ${genrcin} and re-install.

EOF
sed -e 's/@INSTALLER@/'${USER}'/g' "${genrcin}" >> "${genrcout}"

# install powerline fonts
(cd ~/.fonts && ./install.sh)
# install more fonts
cp ${scriptdir}/fonts/* ~/.fonts/

# install p10k
(cd $HOME/.oh-my-zsh/themes && git clone --depth=1 https://github.com/romkatv/powerlevel10k.git)

# fish config
fish -c "set fish_key_bindings fish_vi_key_bindings"
